name: Deploy Strapi with CodeDeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Trigger CodeDeploy Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Register new ECS task definition
        id: register-task
        run: |
          IMAGE_URI=607700977843.dkr.ecr.us-east-2.amazonaws.com/strapi-ecs-kg:latest

          TASK_DEF=$(aws ecs describe-task-definition --task-definition gk-st-task)

          NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$IMAGE_URI" '.taskDefinition | {
            family: .family,
            containerDefinitions: (.containerDefinitions | map(if .name == "strapi" then .image = $IMAGE else . end)),
            executionRoleArn: .executionRoleArn,
            networkMode: .networkMode,
            requiresCompatibilities: .requiresCompatibilities,
            cpu: .cpu,
            memory: .memory
          }')

          echo "$NEW_TASK_DEF" > new-task-def.json

          REVISION=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json | jq -r '.taskDefinition.taskDefinitionArn')

          echo "TASK_DEFINITION=$REVISION" >> $GITHUB_ENV

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name gk-strapi-app \
            --deployment-group-name gk-strapi-deployment-group \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --description "GitHub Actions deployment on $(date)" \
            --revision revisionType=AppSpecContent,appSpecContent="{
              \"content\": \"version: 1\nResources:\n  - TargetService:\n      Type: AWS::ECS::Service\n      Properties:\n        TaskDefinition: ${{ env.TASK_DEFINITION }}\n        LoadBalancerInfo:\n          ContainerName: strapi\n          ContainerPort: 1337\n\",
              \"sha256\": \"\"
            }"

