name: Deploy Strapi to ECS using CodeDeploy Blue/Green

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Register new ECS task definition
        id: register-task
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://ecs-task-def.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Render AppSpec file with Task Definition ARN
        run: |
          sed "s|PLACEHOLDER_TASK_DEF_ARN|$TASK_DEF_ARN|g" appspec.yml > appspec-rendered.yml

      - name: Deploy to ECS via CodeDeploy
        run: |
          CONTENT=$(cat appspec-rendered.yml | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          aws deploy create-deployment \
            --application-name strapi-cd-app-siya \
            --deployment-group-name strapi-cd-dg-siya \
            --revision "{\"revisionType\":\"AppSpecContent\",\"appSpecContent\":{\"content\":\"$CONTENT\"}}" \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce

