      - name: Trigger CodeDeploy Deployment
        run: |
          APP_SPEC=$(cat <<EOF
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "$TASK_DEF_ARN"
        LoadBalancerInfo:
          ContainerName: "strapi"
          ContainerPort: 1337
EOF
          )

          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APP \
            --deployment-group-name $CODEDEPLOY_DEPLOYMENT_GROUP \
            --revision revisionType=AppSpecContent,appSpecContent="{\"content\":\"$(echo "$APP_SPEC" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')\"}" \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --region $AWS_REGION

