- name: Create CodeDeploy Deployment
  id: deploy_cd
  run: |
    echo "Generating AppSpec content..."
    APPSPEC=$(cat <<EOF
{
  "revisionType": "AppSpecContent",
  "appSpecContent": {
    "content": "version: 1.0\nResources:\n  - TargetService:\n      Type: AWS::ECS::Service\n      Properties:\n        TaskDefinition: $TASK_DEF_ARN\n        LoadBalancerInfo:\n          ContainerName: strapi\n          ContainerPort: 1337"
  }
}
EOF
)

    DEPLOYMENT_ID=$(aws deploy create-deployment \
      --application-name "$CODEDEPLOY_APP" \
      --deployment-group-name "$CODEDEPLOY_DEPLOYMENT_GROUP" \
      --cli-input-json "$APPSPEC" \
      --query "deploymentId" --output text)

    echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
    echo "deployment-id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT

