name: CD-Deploy-Terraform-KG

on:
  workflow_run:
    workflows: ["CI-Build-Push-Image-KG"]
    types:
      - completed
  workflow_dispatch:  # Manual trigger for CD

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: cd terraform-blue-green-dep && terraform init

      - name: Terraform Plan
        run: cd terraform-blue-green-dep && terraform plan -out=tfplan

      - name: Terraform Apply
        run: cd terraform-blue-green-dep && terraform apply -auto-approve tfplan

