name: Terraform Apply (Strapi Siya Infra)

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-strapi-siya/**'

  workflow_dispatch:  # Optional: allows manual trigger

env:
  AWS_REGION: us-east-2
  IMAGE_URI: 607700977843.dkr.ecr.us-east-2.amazonaws.com/strapi-ecs-kg:latest

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform-strapi-siya

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="image_uri=${{ env.IMAGE_URI }}" -input=false

      - name: Terraform Apply (auto-approved)
        run: terraform apply -auto-approve -var="image_uri=${{ env.IMAGE_URI }}" -input=false

